### PR TITLE
Docs and usage improvements

### PR DESCRIPTION
**Pull request by mhkarimi1383**
Added K8s/Docker usage
Making docs more understandable
Creating Docker images automatically using GH-Actions to be used with K8s/Docker
Formatting Code
Making more options available to config

> Change docker image names in docs and files after merge (replace `mhkarimi1383` with `anyongjin`) and give GH-Actions access to read and write packages

### CODE REVIEW

**Comment by anyongjin** [comment]
Thank you for helping to improve the documentation and user experience. However, after reviewing the code, I found some issues that need to be resolved before merging. As follows:
1. Please remove the '. idea' project configuration from the submission
2. The Chinese document is damaged. You can just leave it unchanged, and I would update it after merging the commits.

If you don't have time to make changes, I can also reset the submission and delete irrelevant files through the 'git reset -- soft' command, but this would lose your contribution records. So it would be better if you can solve the problesm and resubmitting a new pull request. 
Thank you.

**Comment by mhkarimi1383** [comment]
@anyongjin 
Hi I am still working on my PR (I want to add support for some fields for (e.g. timestamp))
I have just removed the .idea directory since this is a editor/ide specific thing

**Comment by mhkarimi1383** [comment]
@anyongjin 
Hi
I was a bit busy
I have fixed timestamp `def_val`

as for Chinese README  I have just changed the filename and README link according to new filenames
also I have removed `.idea` since it specifically for editor/ide

**Comment by anyongjin** [comment]
@mhkarimi1383 
Maybe I didn't explain it clearly enough. The problems still exists.
1. The `. idea` directory needs to be removed from the submission history, rather than simply deleting and adding a new submission. After merging in this way, there are still records in `. git`. You may want to try `git reset - soft` or `git rebase`, as historical submissions need to be reorganized; Ultimately, it is necessary to ensure that there is no `. idea` folder in [Files Changed](https://github.com/anyongjin/mysql_ibd/pull/17/files).
2. Either `readme.cn.md` or `README CN.md` is fine, case is not important. But the Chinese content in `README.CN.md` which you submitted are garbled. You can just keep them as they were before you made the changes, and I will update them.

Thank you again for your contributions amidst your busy work schedule!

**Comment by mhkarimi1383** [comment]
@anyongjin 


Oh I see

If it's Ok I can remove .idea historically but I have to push force and don't know if you can merge or not

Chinese readme is broken I think because of my formatter I will revert

**Comment by anyongjin** [comment]
@mhkarimi1383 
Docker support is helpful, and documentation improvements are nice, so I will certainly merge once the above two issues are resolved.
Thanks

**Comment by mhkarimi1383** [comment]
@anyongjin 
Chinese Readme back to original content

**Comment by mhkarimi1383** [comment]
@anyongjin
Are you Ok with push force?
I want to remove .idea from history

**Comment by anyongjin** [comment]
Sorry, I've been busy these past two days and haven't logged into Github often.
As I understand it, your forced push only affects your repository, not my repository, because there is no `.idea` folder in my repository's commit history, so there is no need to modify the commit history.
So after you force push to your own repository, submit a pull request, because your commit must be after af0354b820c68a05d74606c4885bf1b5ca75b845, there should be no merge conflict here

**Comment by mhkarimi1383** [comment]
@anyongjin 
Will do it in another branch

**Comment by mhkarimi1383** [comment]
@anyongjin
I can't do force push since it will override history

When I tried to create a PR it gave me 

There isn’t anything to compare.

master and remove-ide-files are entirely different commit histories. 

Error

So please merge my PR then run

```shell
git filter-repo --invert-paths --path .idea --force
git remote add origin git@github.com:anyongjin/mysql_ibd
git push --set-upstream origin master --force
```

Do not forget notes about username is files replace `mhkarimi1383` with `anyongjin` in all of the files

**Comment by anyongjin** [comment]
OK, I merged it first and will modify it later, Thank you very much!

**Comment by anyongjin** [comment]
Can you prepare a Docker image to publish to Docker Hub during your free time? This will make it more convenient for other users who use Docker, and I will update the documentation to guide users to use the image you compiled. 
@mhkarimi1383

**Comment by mhkarimi1383** [comment]
@anyongjin 

If you create a secret for docker hub creds I can update actions to use that

but I would prefer GHCR

**Comment by anyongjin** [comment]
GHCR is fine. I don't know that you have built the GHCR image before I update the readme.md. Everything's ok now

**Comment by mhkarimi1383** [comment]
@anyongjin Yeah just update from my username to your username and give actions required permissions everything is fine

**Comment by mhkarimi1383** [comment]
Update readme and k8s-sample

**Pull request merged**
